# Generated by Django 3.2.9 on 2021-11-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='golfer',
            new_name='name',
        ),
    ]
