# Generated by Django 3.2.9 on 2022-02-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_fivescores'),
    ]

    operations = [
        migrations.AddField(
            model_name='fivescores',
            name='total_score',
            field=models.IntegerField(default=33),
            preserve_default=False,
        ),
    ]
