# Generated by Django 3.2.9 on 2022-03-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_fivescores_total_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_date', models.DateField(null=True)),
            ],
        ),
    ]
