# Generated by Django 3.2.9 on 2022-05-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_scoredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfer',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='name'),
        ),
    ]
